# /// script
# requires-python = ">=3.10"
# dependencies = ["pyyaml"]
# ///
"""Build data.js from the ccf-deadlines repo (https://github.com/ccfddl/ccf-deadlines).

Usage: uv run build_data.py [path/to/ccf-deadlines]   (downloads the repo if no path given)
"""
import io
import json
import re
import sys
import tarfile
import urllib.request
from datetime import date
from pathlib import Path

import yaml

TARBALL = "https://codeload.github.com/ccfddl/ccf-deadlines/tar.gz/refs/heads/main"
MIN_YEAR = 2019
OUT = Path(__file__).with_name("data.js")

MONTH_NAMES = "january february march april may june july august september october november december".split()
TOKEN_RE = re.compile(r"[A-Za-z]+|\d{4}|\d{1,2}")


def month_of(word: str):
    w = word.lower()
    if len(w) < 3:
        return None
    return next((i for i, m in enumerate(MONTH_NAMES, 1) if m.startswith(w)), None)


def parse_range(text: str):
    """Handles "July 28-30, 2025", "June 30 - July 2, 2026", "Sept 26-29, 2023",
    "December 8-10 (Sydney), December 9-11 (Atlanta), 2026", "September, 2024"."""
    years = re.findall(r"\b(20\d\d)\b", text or "")
    if not years:
        return None, None
    y = int(years[-1])
    text = text.replace(years[-1], " ")
    month, days = None, []  # (month, day) pairs in order of appearance
    for tok in TOKEN_RE.findall(text):
        if tok.isdigit():
            if month:
                days.append((month, int(tok)))
        elif (m := month_of(tok)):
            month = m
    try:
        if not days:
            return (date(y, month, 1).isoformat(), None) if month else (None, None)
        (m1, d1), (m2, d2) = days[0], days[-1]
        return date(y if m1 <= m2 else y - 1, m1, d1).isoformat(), date(y, m2, d2).isoformat()
    except ValueError:
        return None, None


def load_source(arg: str | None) -> Path:
    if arg:
        return Path(arg)
    cache = Path(__file__).with_name(".cache")
    print("Downloading ccf-deadlines…", file=sys.stderr)
    data = urllib.request.urlopen(TARBALL, timeout=60).read()
    tarfile.open(fileobj=io.BytesIO(data)).extractall(cache, filter="data")
    return cache / "ccf-deadlines-main"


def clean(v):
    if v is None:
        return None
    s = str(v).strip()
    return None if not s or s.upper() == "TBD" else s


def main():
    root = load_source(sys.argv[1] if len(sys.argv) > 1 else None)
    types = yaml.safe_load((root / "conference" / "types.yml").read_text())
    areas = {t["sub"]: t["name_en"] for t in types}

    confs = []
    for f in sorted((root / "conference").glob("*/*.yml")):
        for c in yaml.safe_load(f.read_text()) or []:
            editions = []
            for e in c.get("confs") or []:
                if int(e.get("year", 0)) < MIN_YEAR:
                    continue
                start, end = parse_range(str(e.get("date", "")))
                deadlines = []
                for t in e.get("timeline") or []:
                    item = {k: clean(t.get(k)) for k in
                            ("abstract_deadline", "deadline", "rebuttal_deadline", "decision_deadline", "comment")}
                    if any(item[k] for k in ("abstract_deadline", "deadline", "decision_deadline")):
                        deadlines.append({k: v for k, v in item.items() if v})
                editions.append({k: v for k, v in {
                    "year": int(e["year"]),
                    "link": clean(e.get("link")),
                    "place": clean(e.get("place")),
                    "dateText": clean(e.get("date")),
                    "start": start,
                    "end": end,
                    "tz": clean(e.get("timezone")) or "AoE",
                    "deadlines": deadlines,
                }.items() if v is not None})
            if not editions:
                continue
            rank = c.get("rank") or {}
            confs.append({
                "id": f.stem,
                "title": str(c["title"]),
                "description": str(c.get("description", "")).strip(),
                "area": c.get("sub"),
                "rank": {k: str(v) for k, v in rank.items() if v and str(v) != "N"},
                "dblp": clean(c.get("dblp")),
                "editions": sorted(editions, key=lambda e: e["year"]),
            })

    payload = {"areas": areas, "conferences": confs}
    OUT.write_text("// Generated by build_data.py from github.com/ccfddl/ccf-deadlines. Do not edit.\n"
                   "window.CONF_DATA = " + json.dumps(payload, ensure_ascii=False, separators=(",", ":")) + ";\n")
    n_ed = sum(len(c["editions"]) for c in confs)
    print(f"Wrote {OUT.name}: {len(confs)} conferences, {n_ed} editions", file=sys.stderr)


if __name__ == "__main__":
    main()
